services:
  - type: web
    name: bumblebee-pair-code
    env: docker
    plan: free
    branch: main
    repo: https://github.com/khalid-official/pair-code
    dockerfilePath: ./Dockerfile
    autoDeploy: true
